# Generated by Django 5.2.7 on 2025-10-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre.actor",
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="genre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="theatre.genre",
            ),
        ),
    ]
