# Generated by Django 5.2.7 on 2025-10-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_play_actor_play_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="play",
            name="actor",
        ),
        migrations.AddField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(
                blank=True, related_name="plays", to="theatre.actor"
            ),
        ),
    ]
